<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CopyStart.Application</RootNamespace>
    <AssemblyName>CopyStart.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CopyStart.Domain\CopyStart.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.FluentValidation" />
  </ItemGroup>

</Project>
