#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
ENV TZ=America/Bogota
ENV ASPNETCORE_URLS=http://+:5000
WORKDIR /app
EXPOSE 5009

WORKDIR /src
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY . .
RUN dotnet restore "CopyStart/CopyStart.csproj"
COPY . .
WORKDIR "/CopyStart"
RUN dotnet build "CopyStart.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CopyStart.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CopyStart.dll"]
