// <auto-generated />
using System;
using CopyStart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CopyStart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220704014536_AddFieldTiempoEjecucionInProcedimientos")]
    partial class AddFieldTiempoEjecucionInProcedimientos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CopyStart.Entities.Activo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MarcaActivoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloActivoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TipoActivoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarcaActivoId");

                    b.HasIndex("ModeloActivoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoActivoId");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "ADMIN",
                            ConcurrencyStamp = "117f86aa-60d5-458c-b004-e297caee8119",
                            Name = "Administrador",
                            NormalizedName = "Administrador"
                        },
                        new
                        {
                            Id = "COORD",
                            ConcurrencyStamp = "f411b036-53e6-424f-b5a0-536c39118729",
                            Name = "Coordinador",
                            NormalizedName = "Coordinador"
                        },
                        new
                        {
                            Id = "TEC",
                            ConcurrencyStamp = "d680c320-42ef-4c8f-bd23-9f9b00624327",
                            Name = "Tecnico",
                            NormalizedName = "Tecnico"
                        },
                        new
                        {
                            Id = "CLN",
                            ConcurrencyStamp = "eb1b4a84-171e-4092-87ee-3a02ba233c29",
                            Name = "Cliente",
                            NormalizedName = "Cliente"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonaId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PersonaId");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1cf68c49-edd7-4d24-ab0c-b14c6aef0ebe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce435a30-8d16-4770-a7fb-118fab13767b",
                            Email = "cpadmin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "CPADMIN@YOPMAIL.COM",
                            NormalizedUserName = "CPADMIN@YOPMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBIHivGCDTDdkfSc8TsymI3VtOklfVojN8214LrcTyQWK3lqIRWJ7AHFQMne9rXm0g==",
                            PersonaId = new Guid("510c6b6e-a475-488c-9bd9-84a6215da1cb"),
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SVKHSIPWR4JE76RDYMGA7MQGFIIBR3TX",
                            TwoFactorEnabled = false,
                            UserName = "cpadmin@yopmail.com"
                        },
                        new
                        {
                            Id = "5c141fdd-ab2f-49be-8a31-43aec63f918f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "776e1d1a-0c3c-41b0-bb44-bcb151add354",
                            Email = "CPCOORDINADOR@yopmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "CPCOORDINADOR@YOPMAIL.COM",
                            NormalizedUserName = "CPCOORDINADOR@YOPMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDv98UwloGC1tI3Elt0TgyWk9DxWPi475t9/P2SOAO/TgHilR1/Tnp0kQpnctazOJw==",
                            PersonaId = new Guid("f8d8b32a-7fad-43e1-a35e-e5a52621594d"),
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "RZABU4JPNDQVJF4LWR5ZS755BS7H6HDR",
                            TwoFactorEnabled = false,
                            UserName = "cpcoordinador@yopmail.com"
                        },
                        new
                        {
                            Id = "3cbfb0a7-d323-4f84-9d14-daeef363f947",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa35d6da-54e6-476b-8810-4a182b8b07de",
                            Email = "user3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "USER3@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHRn5OJw1NKAwjB4w6dEsVjB2qi/bOR+8/WbmTjTa8lQCvTy6Xg4WqMtm6A/yYYxDw==",
                            PersonaId = new Guid("2481e6f4-7aeb-43bf-8dac-e57c1d1568ed"),
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4LNTJIEMTON6KDXWASKMDXTFM2BCUCH6",
                            TwoFactorEnabled = false,
                            UserName = "user3@gmail.com"
                        },
                        new
                        {
                            Id = "cacd6063-c77d-437e-8cad-2e97ba1a0a6a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3330e49-ac28-4952-a50a-a30e8222aed7",
                            Email = "user4@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER4@GMAIL.COM",
                            NormalizedUserName = "USER4@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGAsB2jMI6Q3cJTunTexm1lX3qqiVzHMV9sDws+mh3JcqAGY2og313y5uNjZ+32OAg==",
                            PersonaId = new Guid("8af22848-85fb-4c50-9d7d-1137fd84eb98"),
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WJR7XMGC332UT234BG7O35M6MIIGKQ2Q",
                            TwoFactorEnabled = false,
                            UserName = "user4@gmail.com"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "1cf68c49-edd7-4d24-ab0c-b14c6aef0ebe",
                            RoleId = "ADMIN"
                        },
                        new
                        {
                            UserId = "5c141fdd-ab2f-49be-8a31-43aec63f918f",
                            RoleId = "COORD"
                        },
                        new
                        {
                            UserId = "3cbfb0a7-d323-4f84-9d14-daeef363f947",
                            RoleId = "TEC"
                        },
                        new
                        {
                            UserId = "cacd6063-c77d-437e-8cad-2e97ba1a0a6a",
                            RoleId = "CLN"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("CopyStart.Entities.Diagnostico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("FechaDiagnostico")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SoportesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SoportesId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("CopyStart.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Peso")
                        .IsRequired()
                        .HasColumnType("double precision");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("CopyStart.Entities.MarcaActivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TipoActivoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoActivoId");

                    b.ToTable("MarcaActivos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b5de1c4-7bd1-444f-8f22-cab2cc0dcfdd"),
                            Codigo = "RICOH",
                            Descripcion = "",
                            Estado = true,
                            Nombre = "Ricoh",
                            TipoActivoId = new Guid("f443468f-26a6-4e4c-a9c5-77de2953f802")
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.ModeloActivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MarcaActivoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaActivoId");

                    b.ToTable("ModeloActivos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ca30cec-d049-4144-8cf1-6ec4e90f4b57"),
                            Codigo = "A2345",
                            Descripcion = "",
                            Estado = true,
                            MarcaActivoId = new Guid("0b5de1c4-7bd1-444f-8f22-cab2cc0dcfdd"),
                            Nombre = "Aficio 2345"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uuid");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("510c6b6e-a475-488c-9bd9-84a6215da1cb"),
                            Apellidos = "Por defecto",
                            Direccion = "Calle 40, #33-18",
                            Nombres = "Administrador",
                            NumeroDocumento = "1234567890",
                            Telefono = 3188743948L,
                            TipoDocumentoId = new Guid("324df0a1-337d-45c4-bf79-eb3a01e14273"),
                            UbicacionId = 50001
                        },
                        new
                        {
                            Id = new Guid("f8d8b32a-7fad-43e1-a35e-e5a52621594d"),
                            Apellidos = "Por defecto",
                            Direccion = "Calle 40, #33-18",
                            Nombres = "Coordinador",
                            NumeroDocumento = "1234567890",
                            Telefono = 3188743948L,
                            TipoDocumentoId = new Guid("324df0a1-337d-45c4-bf79-eb3a01e14273"),
                            UbicacionId = 50001
                        },
                        new
                        {
                            Id = new Guid("2481e6f4-7aeb-43bf-8dac-e57c1d1568ed"),
                            Apellidos = "Por defecto",
                            Direccion = "Calle 40, #33-18",
                            Nombres = "Tecnico",
                            NumeroDocumento = "1234567890",
                            Telefono = 3188743948L,
                            TipoDocumentoId = new Guid("324df0a1-337d-45c4-bf79-eb3a01e14273"),
                            UbicacionId = 50001
                        },
                        new
                        {
                            Id = new Guid("8af22848-85fb-4c50-9d7d-1137fd84eb98"),
                            Apellidos = "Por defecto",
                            Direccion = "Calle 40, #33-18",
                            Nombres = "Cliente",
                            NumeroDocumento = "1234567890",
                            Telefono = 3188743948L,
                            TipoDocumentoId = new Guid("324df0a1-337d-45c4-bf79-eb3a01e14273"),
                            UbicacionId = 50001
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.Procedimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TiempoEjecucion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Procedimientos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29c31d04-82cd-4fdb-9470-9fa95a22e2f0"),
                            Codigo = "AMAQ",
                            Descripcion = "",
                            Estado = true,
                            Nombre = "Abrir maquina",
                            TiempoEjecucion = 10
                        },
                        new
                        {
                            Id = new Guid("d86abe63-f8ae-4b6c-9ad9-b10db92f9f01"),
                            Codigo = "RCOMP",
                            Descripcion = "",
                            Estado = true,
                            Nombre = "Revisar componentes",
                            TiempoEjecucion = 20
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.ProcedimientoTipoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcedimientoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.HasIndex("TipoServicioId", "Numero")
                        .IsUnique();

                    b.HasIndex("TipoServicioId", "ProcedimientoId")
                        .IsUnique();

                    b.ToTable("ProcedimientosTipoServicios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f3a8930-b64a-4cd8-beec-0c539551ea6a"),
                            Numero = 1,
                            ProcedimientoId = new Guid("29c31d04-82cd-4fdb-9470-9fa95a22e2f0"),
                            TipoServicioId = new Guid("64b5a31e-0d62-42d4-82d2-2eef76330d9d")
                        },
                        new
                        {
                            Id = new Guid("a35d9139-39dd-4fa2-b1a4-9dc64358c27a"),
                            Numero = 2,
                            ProcedimientoId = new Guid("d86abe63-f8ae-4b6c-9ad9-b10db92f9f01"),
                            TipoServicioId = new Guid("64b5a31e-0d62-42d4-82d2-2eef76330d9d")
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.Repuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("CopyStart.Entities.RepuestoProcedimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcedimientoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepuestoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("RepuestosProcedimientos");
                });

            modelBuilder.Entity("CopyStart.Entities.Servicio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ActivoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DiagnosticoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("SolicitudId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SoportesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipoServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("DiagnosticoId");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("SoportesId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("CopyStart.Entities.ServicioProcedimientoTipoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcedimientoTipoServicioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ProcedimientosRealizados")
                        .HasColumnType("boolean");

                    b.Property<long>("ServicioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcedimientoTipoServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("ServiciosProcedimientosTipoServicios");
                });

            modelBuilder.Entity("CopyStart.Entities.Solicitud", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ActivoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EstadoSolicitud")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Incidencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Motivo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("CopyStart.Entities.Soporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CopiaFacturaFirmadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentoCertificacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentoFacturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentoReciboId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReciboId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoCertificacionId");

                    b.HasIndex("DocumentoFacturaId");

                    b.HasIndex("ReciboId");

                    b.ToTable("Soportes");
                });

            modelBuilder.Entity("CopyStart.Entities.TipoActivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposActivo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f443468f-26a6-4e4c-a9c5-77de2953f802"),
                            Codigo = "IMP",
                            Descripcion = "",
                            Estado = true,
                            Nombre = "Impresora"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumento");

                    b.HasData(
                        new
                        {
                            Id = new Guid("324df0a1-337d-45c4-bf79-eb3a01e14273"),
                            Codigo = "CC",
                            Descripcion = "CC",
                            Estado = true,
                            Nombre = "Cedula de Ciudadania"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.TipoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TipoActivoId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoActivoId");

                    b.ToTable("TiposServicio");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64b5a31e-0d62-42d4-82d2-2eef76330d9d"),
                            Codigo = "PCMAN",
                            Descripcion = "",
                            Estado = true,
                            Nombre = "Mantenimiento de impresora",
                            TipoActivoId = new Guid("f443468f-26a6-4e4c-a9c5-77de2953f802")
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.Ubicacion", b =>
                {
                    b.Property<int>("CodigoLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Lugar")
                        .HasColumnType("text");

                    b.HasKey("CodigoLugar");

                    b.ToTable("Ubicaciones");

                    b.HasData(
                        new
                        {
                            CodigoLugar = 50001,
                            Lugar = "Villavicencio"
                        });
                });

            modelBuilder.Entity("CopyStart.Entities.Activo", b =>
                {
                    b.HasOne("CopyStart.Entities.MarcaActivo", "MarcaActivo")
                        .WithMany()
                        .HasForeignKey("MarcaActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.ModeloActivo", "ModeloActivo")
                        .WithMany()
                        .HasForeignKey("ModeloActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.TipoActivo", "TipoActivo")
                        .WithMany()
                        .HasForeignKey("TipoActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarcaActivo");

                    b.Navigation("ModeloActivo");

                    b.Navigation("Persona");

                    b.Navigation("TipoActivo");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationRoleClaim", b =>
                {
                    b.HasOne("CopyStart.Entities.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUser", b =>
                {
                    b.HasOne("CopyStart.Entities.Persona", "Persona")
                        .WithMany("Users")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserClaim", b =>
                {
                    b.HasOne("CopyStart.Entities.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserLogin", b =>
                {
                    b.HasOne("CopyStart.Entities.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("CopyStart.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUserToken", b =>
                {
                    b.HasOne("CopyStart.Entities.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CopyStart.Entities.Diagnostico", b =>
                {
                    b.HasOne("CopyStart.Entities.Soporte", "Soportes")
                        .WithMany()
                        .HasForeignKey("SoportesId");

                    b.Navigation("Soportes");
                });

            modelBuilder.Entity("CopyStart.Entities.MarcaActivo", b =>
                {
                    b.HasOne("CopyStart.Entities.TipoActivo", "TipoActivo")
                        .WithMany()
                        .HasForeignKey("TipoActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoActivo");
                });

            modelBuilder.Entity("CopyStart.Entities.ModeloActivo", b =>
                {
                    b.HasOne("CopyStart.Entities.MarcaActivo", "MarcaActivo")
                        .WithMany()
                        .HasForeignKey("MarcaActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MarcaActivo");
                });

            modelBuilder.Entity("CopyStart.Entities.Persona", b =>
                {
                    b.HasOne("CopyStart.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("CopyStart.Entities.ProcedimientoTipoServicio", b =>
                {
                    b.HasOne("CopyStart.Entities.Procedimiento", "Procedimientos")
                        .WithMany()
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimientos");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("CopyStart.Entities.RepuestoProcedimiento", b =>
                {
                    b.HasOne("CopyStart.Entities.Procedimiento", "Procedimientos")
                        .WithMany()
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Repuesto", "Repuesto")
                        .WithMany()
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimientos");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("CopyStart.Entities.Servicio", b =>
                {
                    b.HasOne("CopyStart.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Diagnostico", "Diagnostico")
                        .WithMany()
                        .HasForeignKey("DiagnosticoId");

                    b.HasOne("CopyStart.Entities.Solicitud", "Solicitudes")
                        .WithMany()
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Soporte", "Soportes")
                        .WithMany()
                        .HasForeignKey("SoportesId");

                    b.HasOne("CopyStart.Entities.TipoServicio", "TipoServicios")
                        .WithMany()
                        .HasForeignKey("TipoServicioId");

                    b.Navigation("Activo");

                    b.Navigation("Diagnostico");

                    b.Navigation("Solicitudes");

                    b.Navigation("Soportes");

                    b.Navigation("TipoServicios");
                });

            modelBuilder.Entity("CopyStart.Entities.ServicioProcedimientoTipoServicio", b =>
                {
                    b.HasOne("CopyStart.Entities.ProcedimientoTipoServicio", "ProcedimientoTipoServicio")
                        .WithMany()
                        .HasForeignKey("ProcedimientoTipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcedimientoTipoServicio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("CopyStart.Entities.Solicitud", b =>
                {
                    b.HasOne("CopyStart.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Persona", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Persona", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId");

                    b.HasOne("CopyStart.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Cliente");

                    b.Navigation("Tecnico");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("CopyStart.Entities.Soporte", b =>
                {
                    b.HasOne("CopyStart.Entities.Documento", "DocumentoCertificacion")
                        .WithMany()
                        .HasForeignKey("DocumentoCertificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CopyStart.Entities.Documento", "CopiaFacturaFirmada")
                        .WithMany()
                        .HasForeignKey("DocumentoFacturaId");

                    b.HasOne("CopyStart.Entities.Documento", "DocumentoRecibo")
                        .WithMany()
                        .HasForeignKey("ReciboId");

                    b.Navigation("CopiaFacturaFirmada");

                    b.Navigation("DocumentoCertificacion");

                    b.Navigation("DocumentoRecibo");
                });

            modelBuilder.Entity("CopyStart.Entities.TipoServicio", b =>
                {
                    b.HasOne("CopyStart.Entities.TipoActivo", "TipoActivo")
                        .WithMany()
                        .HasForeignKey("TipoActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoActivo");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CopyStart.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CopyStart.Entities.Persona", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
